# This is an example project for how to use the sra_convert pipeline to convert
# .sra files to .bam files using looper.

metadata:
  output_dir: ${PROCESSED}pepsra
  sample_annotation: ${SRAMETA}annocomb_GSE52457.csv
  pipeline_interfaces: pipeline_interface_convert.yaml
  sample_subannotation: ${SRAMETA}allmerge_GSE52457.csv

derived_columns: [data_source]

data_sources:
  SRA: "${SRARAW}{SRR}.sra"
